"""Reproducible validation of rolloutscope detectors against Patronus TRACE.

TRACE (arXiv:2601.20103, https://huggingface.co/datasets/PatronusAI/trace-dataset)
is a labeled reward-hacking benchmark of coding-agent trajectories. The dataset
card is explicit that the trajectories are synthetically generated by Claude Code
and human verified, with simulated tool use, so a number measured here says
something about detection on realistic transcripts and nothing yet about
detection on operational RL logs.

This script is a thin wrapper. Every decision that could move a number lives in
:mod:`rolloutscope.benchmark` and is shared with ``tests/integration``: the row
mapping, the applicability rules, the metric definitions, and the frozen
manifest. Running the two against the same manifest and split must produce the
same table.

Usage:

    uv run --extra benchmark python scripts/trace_validation.py
    uv run --extra benchmark python scripts/trace_validation.py --split holdout
    uv run --extra benchmark python scripts/trace_validation.py --json out.json

The default split is ``tuning``. The holdout is sealed on purpose: it is the
partition an accuracy claim will eventually come from, and measuring it while
the Phase 2 detector repairs are still open would spend it for nothing.

The dataset is gated, so a Hugging Face token is required: put ``HF_TOKEN`` in a
``.env`` file at the repository root, or export it. The script skips (prints a
reason and exits 0) whenever the network, the license, or the row shape does not
cooperate, so it is safe to run anywhere.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from rolloutscope.benchmark import (
    BenchmarkUnavailable,
    evaluate_rows,
    load_dotenv_token,
    load_manifest,
    load_rows,
    render_text,
    report_to_json,
)
from rolloutscope.detectors import DetectorConfig, discover_detectors

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "benchmarks" / "trace" / "manifest.json"

HOLDOUT_WARNING = (
    "The holdout partition was evaluated. Record the result as a one-off "
    "measurement, not as a threshold source: a threshold fitted to the holdout "
    "stops being a holdout number."
)


def main() -> int:
    """Fetch, evaluate, and print the benchmark table; return the exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--split",
        default="tuning",
        choices=("train", "tuning", "holdout", "all"),
        help="manifest split to evaluate (default: tuning; holdout is sealed)",
    )
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    parser.add_argument("--json", type=Path, default=None, help="also write the report as JSON")
    args = parser.parse_args()

    if not args.manifest.is_file():
        print(f"SKIP: no manifest at {args.manifest}; run scripts/build_trace_manifest.py first")
        return 0
    manifest = load_manifest(args.manifest)

    load_dotenv_token(REPO_ROOT)
    try:
        rows, source, _ = load_rows(revision=manifest.dataset.revision)
    except BenchmarkUnavailable as exc:
        print(f"SKIP: {exc}")
        return 0

    notes = []
    if source != "parquet":
        notes.append(
            "Rows came from the datasets-server rows API, which takes no revision "
            "argument. The per-row hash check below is what establishes that these "
            "are the pinned rows."
        )
    if args.split == "holdout":
        notes.append(HOLDOUT_WARNING)

    report = evaluate_rows(
        rows,
        manifest,
        discover_detectors(),
        DetectorConfig(),
        split=None if args.split == "all" else args.split,
        source=source,
        notes=notes,
    )
    print(render_text(report))
    if args.json is not None:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(report_to_json(report), encoding="utf-8")
        print(f"wrote {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
