"""Fixture separation metrics: every detector must separate its labeled pair.

Runs every detector over every labeled fixture file and writes a per-detector
precision/recall table to tests/artifacts/detector_fixture_metrics.txt. The
file-level convention: a file counts as predicted-positive for a detector when
any of its verdicts fired on that file. For detector D:

- TP: D fires on its own hacked file(s)
- FN: D stays silent on its own hacked file(s)
- FP: D fires on ANY detector's clean file (clean files are designed to be
  globally clean, not just clean for their own detector)
- TN: D stays silent on a clean file

Fires on another detector's hacked file are neither TP nor FP (those files are
unlabeled for D) and are reported informationally as cross-fires.
"""

from __future__ import annotations

from pathlib import Path

from rolloutscope.detectors import DetectorConfig, load_detectors
from rolloutscope.schema import read_rollouts

LABELED_DIR = Path(__file__).parent.parent / "fixtures" / "labeled"


def test_fixture_metrics_artifact(artifacts_dir):
    detectors = load_detectors()
    assert detectors, "entry-point discovery returned no detectors"
    config = DetectorConfig()
    files = sorted(LABELED_DIR.glob("*.jsonl"))
    assert files, "no labeled fixtures found"

    fired_on: dict[str, set[str]] = {name: set() for name in detectors}
    for path in files:
        rollouts = list(read_rollouts(path))
        for name, detector in detectors.items():
            verdicts = detector.detect(rollouts, config)
            if any(v.fired for v in verdicts):
                fired_on[name].add(path.stem)

    clean_stems = [p.stem for p in files if p.stem.endswith("_clean")]
    lines = [
        "rolloutscope detector fixture metrics (synthetic labeled fixtures)",
        "generated by tests/test_detectors/test_fixture_metrics.py",
        "",
        "File-level convention: predicted-positive means any verdict fired on the",
        "file. TP/FN are over the detector's own hacked file(s); FP/TN are over",
        "ALL clean files (they are designed to be globally clean). Fires on other",
        "detectors' hacked files are informational cross-fires only.",
        "",
        f"{'detector':<34} {'TP':>3} {'FN':>3} {'FP':>3} {'TN':>3} "
        f"{'precision':>9} {'recall':>6}  cross-fires",
    ]
    failures: list[str] = []
    for name in sorted(detectors):
        own_hacked = [p.stem for p in files if p.stem == f"{name}_hacked"]
        assert own_hacked, f"no hacked fixture found for {name}"
        tp = sum(stem in fired_on[name] for stem in own_hacked)
        fn = len(own_hacked) - tp
        fp = sum(stem in fired_on[name] for stem in clean_stems)
        tn = len(clean_stems) - fp
        cross = sorted(
            stem for stem in fired_on[name] if stem.endswith("_hacked") and stem not in own_hacked
        )
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        lines.append(
            f"{name:<34} {tp:>3} {fn:>3} {fp:>3} {tn:>3} "
            f"{precision:>9.2f} {recall:>6.2f}  {', '.join(cross) or '-'}"
        )
        if fn:
            failures.append(f"{name} missed its hacked fixture")
        if fp:
            failures.append(f"{name} fired on clean fixture(s)")

    artifact = artifacts_dir / "detector_fixture_metrics.txt"
    artifact.write_text("\n".join(lines) + "\n")

    assert not failures, "; ".join(failures)
